runtime: python27
service: uploadfile
# entrypoint: gunicorn -t 0 -b :$PORT main:app
manual_scaling:
  instances: 1

threadsafe: yes
handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE