 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/still-chassis-302715/myimage:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/still-chassis-302715/myimage:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'myimage:'
   - '--image'
   - 'gcr.io/still-chassis-302715/myimage:$COMMIT_SHA'
   - '--region'
   - 'asia-east1'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/still-chassis-302715/myimage:$COMMIT_SHA'